import 'package:get/get.dart';

class Localization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en': {
'piBleName': 'cuckoo-clock',
'auth.signInButton': 'Sign In',
'auth.signUpButton': 'Sign Up',
'auth.resetPasswordButton': 'Send Password Reset',
'auth.emailFormField': 'Email',
'auth.passwordFormField': 'Password',
'auth.nameFormField': 'Name',
'auth.signInErrorTitle': 'Sign In Error',
'auth.signInError': 'Login failed: email or password incorrect.',
'auth.resetPasswordLabelButton': 'Forgot password?',
'auth.signUpLabelButton': 'Create an Account',
'auth.signUpErrorTitle': 'Sign Up Failed.',
'auth.signUpError': 'There was a problem signing up.  Please try again later.',
'auth.signInLabelButton': 'Have an Account? Sign In.',
'auth.resetPasswordNoticeTitle': 'Password Reset Email Sent',
'auth.resetPasswordNotice': 'Check your email and follow the instructions to reset your password.',
'auth.resetPasswordFailed': 'Password Reset Email Failed',
'auth.signInonResetPasswordLabelButton': 'Sign In',
'auth.updateUser': 'Update Profile',
'auth.updateUserSuccessNoticeTitle': 'User Updated',
'auth.updateUserSuccessNotice': 'User information successfully updated.',
'auth.updateUserEmailInUse': 'That email address already has an account.',
'auth.updateUserFailNotice': 'Failed to update user',
'auth.enterPassword': 'Enter your password',
'auth.cancel': 'Cancel',
'auth.submit': 'Submit',
'auth.changePasswordLabelButton': 'Change Password',
'auth.resetPasswordTitle': 'Reset Password',
'auth.updateProfileTitle': 'Update Profile',
'auth.wrongPasswordNoticeTitle': 'Login Failed',
'auth.wrongPasswordNotice': 'The password does not match our records.',
'auth.unknownError': 'Unknown Error',
'settings.title': 'Settings',
'settings.language': 'Language',
'settings.theme': 'Theme',
'settings.signOut': 'Sign Out',
'settings.dark': 'Dark',
'settings.light': 'Light',
'settings.system': 'System',
'settings.updateProfile': 'Update Profile',
'home.title': 'Home',
'home.nameLabel': 'Name',
'home.uidLabel': 'UID',
'home.emailLabel': 'Email',
'home.adminUserLabel': 'Admin User',
'home.permissions': 'Bluetooth',
'home.permissions.approve': 'Approve',
'home.permissions.granted': 'The app requires permissions to use Bluetooth',
'app.title': 'Flutter Starter Project',
'validator.email': 'Please enter a valid email address.',
'validator.password': 'Password must be at least 6 characters.',
'validator.name': 'Please enter a name.',
'validator.number': 'Please enter a number.',
'validator.notEmpty': 'This is a required field.',
'validator.amount': 'Please enter a number i.e. 250 - no dollar symbol and no cents',
},
'de': {
'piBleName': 'cuckoo-clock',
'auth.signInButton': 'Einloggen',
'auth.signUpButton': 'Anmeldung',
'auth.resetPasswordButton': 'Senden Passwort zurücksetzen',
'auth.emailFormField': 'Email',
'auth.passwordFormField': 'Passwort',
'auth.nameFormField': 'Name',
'auth.signInErrorTitle': 'Anmelden Fehler',
'auth.signInError': 'Fehler bei der Anmeldung: E-Mail oder Passwort falsch.',
'auth.resetPasswordLabelButton': 'Passwort vergessen?',
'auth.signUpLabelButton': 'Ein Konto erstellen',
'auth.signUpErrorTitle': 'Anmeldung gescheitert.',
'auth.signUpError': 'Es gab ein Problem anmeldest. Bitte versuchen Sie es später noch einmal.',
'auth.signInLabelButton': 'Ein Konto haben? Einloggen.',
'auth.resetPasswordNoticeTitle': 'Passwort zurücksetzen E-Mail gesendet',
'auth.resetPasswordNotice': 'Überprüfen Sie Ihre E-Mail und folgen Sie den Anweisungen, um Ihr Passwort zurücksetzen können.',
'auth.resetPasswordFailed': 'Passwort zurücksetzen E-Mail fehlgeschlagen',
'auth.signInonResetPasswordLabelButton': 'Einloggen',
'auth.updateUser': 'Profil aktualisieren',
'auth.updateUserSuccessNoticeTitle': 'Benutzer Aktualisiert',
'auth.updateUserSuccessNotice': 'Benutzerinformationen erfolgreich aktualisiert.',
'auth.updateUserEmailInUse': 'Die E-Mail-Adresse hat bereits ein Konto.',
'auth.updateUserFailNotice': 'Fehler beim Update Benutzer',
'auth.enterPassword': 'Geben Sie Ihr Passwort',
'auth.cancel': 'Stornieren',
'auth.submit': 'einreichen',
'auth.changePasswordLabelButton': 'Kennwort ändern',
'auth.resetPasswordTitle': 'Passwort zurücksetzen',
'auth.updateProfileTitle': 'Profil aktualisieren',
'auth.wrongPasswordNoticeTitle': 'Fehler bei der Anmeldung',
'auth.wrongPasswordNotice': 'Das Passwort nicht unsere entsprechenden Datensätze gefunden.',
'auth.unknownError': 'Unbekannter Fehler',
'settings.title': 'die Einstellungen',
'settings.language': 'Sprache',
'settings.theme': 'Thema',
'settings.signOut': 'Austragen',
'settings.dark': 'Dunkel',
'settings.light': 'Licht',
'settings.system': 'System',
'settings.updateProfile': 'Profil aktualisieren',
'home.title': 'Zuhause',
'home.nameLabel': 'Name',
'home.uidLabel': 'UID',
'home.emailLabel': 'Email',
'home.adminUserLabel': 'Admin Benutzer',
'home.permissions': 'Bluetooth',
'home.permissions.approve': 'Genehmigen',
'home.permissions.granted': 'Die App erfordert Berechtigungen, um Bluetooth zu verwenden',
'app.title': 'Flutter Starter-Projekt',
'validator.email': 'Bitte geben Sie eine gültige E-Mail-Adresse ein.',
'validator.password': 'Passwort muss mindestens 6 Zeichen lang sein.',
'validator.name': 'Bitte geben Sie einen Namen.',
'validator.number': 'Bitte gebe eine Nummer ein.',
'validator.notEmpty': 'Dies ist ein Pflichtfeld.',
'validator.amount': 'Bitte geben Sie eine Zahl das heißt 250 - kein Dollar-Symbol und keinen Cent',
},
'ru': {
'piBleName': 'Часы с кукушкой',
'auth.signInButton': 'Войти',
'auth.signUpButton': 'Зарегистрироваться',
'auth.resetPasswordButton': 'Отправить Сброс пароля',
'auth.emailFormField': 'Электронное письмо',
'auth.passwordFormField': 'Пароль',
'auth.nameFormField': 'Имя',
'auth.signInErrorTitle': 'Ошибка входа',
'auth.signInError': 'Войти не удалось: адрес электронной почты или пароль неверен.',
'auth.resetPasswordLabelButton': 'забыл пароль?',
'auth.signUpLabelButton': 'Завести аккаунт',
'auth.signUpErrorTitle': 'Регистрация прошла неудачно.',
'auth.signUpError': 'Была проблема подписания. Пожалуйста, повторите попытку позже.',
'auth.signInLabelButton': 'Иметь аккаунт? Войти.',
'auth.resetPasswordNoticeTitle': 'Сброс пароля Email Sent',
'auth.resetPasswordNotice': 'Проверьте электронную почту и следуйте инструкциям, чтобы сбросить пароль.',
'auth.resetPasswordFailed': 'Сброс пароля Email Failed',
'auth.signInonResetPasswordLabelButton': 'Войти',
'auth.updateUser': 'Обновить профиль',
'auth.updateUserSuccessNoticeTitle': 'Пользователь Обновлено',
'auth.updateUserSuccessNotice': 'Информация о пользователе успешно обновлена.',
'auth.updateUserEmailInUse': 'Этот адрес электронной почты уже есть учетная запись.',
'auth.updateUserFailNotice': 'Не удался пользователь обновления',
'auth.enterPassword': 'Введите свой пароль',
'auth.cancel': 'Отмена',
'auth.submit': 'Представлять на рассмотрение',
'auth.changePasswordLabelButton': 'Измени пароль',
'auth.resetPasswordTitle': 'Сброс пароля',
'auth.updateProfileTitle': 'Обновить профиль',
'auth.wrongPasswordNoticeTitle': 'Ошибка входа',
'auth.wrongPasswordNotice': 'Пароль не соответствует нашим данным.',
'auth.unknownError': 'Неизвестная ошибка',
'settings.title': 'Настройки',
'settings.language': 'Язык',
'settings.theme': 'Тема',
'settings.signOut': 'Выход',
'settings.dark': 'Темный',
'settings.light': 'Свет',
'settings.system': 'Система',
'settings.updateProfile': 'Обновить профиль',
'home.title': 'Дом',
'home.nameLabel': 'Имя',
'home.uidLabel': 'UID',
'home.emailLabel': 'Электронное письмо',
'home.adminUserLabel': 'Пользователь Admin',
'home.permissions': 'Bluetooth',
'home.permissions.approve': 'Разрешить',
'home.permissions.granted': 'Приложению требуются разрешения на использование Bluetooth',
'app.title': 'Проект флаттер Starter',
'validator.email': 'Пожалуйста, введите действительный адрес электронной почты.',
'validator.password': 'Пароль должен быть не менее 6 символов.',
'validator.name': 'Пожалуйста, введите имя.',
'validator.number': 'Пожалуйста, введите номер.',
'validator.notEmpty': 'Это поле обязательно для заполнения.',
'validator.amount': 'Пожалуйста, введите номер 250 - т.е. без символа доллара и ни цента',
},
        };
      }
      