name: getx_template
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: any
  http: any
  csv: any
  crypto: any
  hive:
  hive_flutter:
  freezed_annotation: any
  permission_handler:
  json_serializable:
  logger:
  get: 
    git: https://github.com/jonataslaw/getx
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: any
  hive_generator: any
  build_runner: any
  freezed: any
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/default.png
    - assets/images/defaultDark.png
  uses-material-design: true

